### PR TITLE
Decoupled Design DLL to make toolkit easier to use

### PR DESCRIPTION
**Pull request by Wagnerp**

### CODE REVIEW

**Comment by herledant** [comment]
Hello,

Maybe it is a silly question but how to compil now with decoupled design?
I obtain reference to design error whan i try to compil this version.
Thank's for answer.

Br

**Comment by BBrouns** [comment]
This seems to have broken the solution? 
There are still quite some references to Krypton.Design in the other projects.

**Comment by Wagnerp** [comment]
There might be some references in the code that might point back to the original  Design DLL. If so they will need to be altered to account for these changes.

@ComponentFactory 
I'll put in a pull request shortly that will have the unaltered designer, until I can find time to make these changes.

**Comment by Wagnerp** [comment]
Yes there are still hard coded references pointing back to Krypton.Design. Easy to fix, but will take time to sort out. Sorry for not catching this earlier.

**Comment by Wagnerp** [comment]
Almost eradicated Design references!

**Comment by megakraken** [comment]
Solution in latest commit is still broken and can no longer be compiled. Please fix @Wagnerp

**Comment by Wagnerp** [comment]
@megakraken, I've reinstated the design code. So it's up to @ComponentFactory to merge the changes. So its not up to me now... sorry.

**Pull request merged**
